// GENERATED by scripts/generate-migration-manifest.ts — do not edit by hand.
// Regenerate after adding a migration: pnpm db:manifest
export interface MigrationManifestEntry {
  filename: string;
  sha256: string;
}

export const EXPECTED_MIGRATIONS: readonly MigrationManifestEntry[] = [
  {
    filename: '001_foundation.sql',
    sha256: '96d8838feaca832ae8dcd294ae374e1211f4f8ded43f24fd54a323aa5d1e7dd6',
  },
  {
    filename: '002_billing.sql',
    sha256: 'cc8c7f1a862c912838e20532aeb6a4fd023821dfcc45e7abd1b95028a7abeaab',
  },
  {
    filename: '003_portal.sql',
    sha256: '6b5ea7d8c7588d8f3452393d517c64df8c3b0b313b86dbdb954a595bf3117e8c',
  },
  {
    filename: '004_vault.sql',
    sha256: 'f09971cec2fe8b48a639a6e5c4de53e1a27160cf8759d926f18f10fd762dd6ef',
  },
  {
    filename: '005_custom_pricing.sql',
    sha256: 'fbf72291d12d4ff1ca9194cc0f70921a881260b3b191426c1e56ac60e0c05c8d',
  },
  {
    filename: '006_pricing_onboarding_tasks.sql',
    sha256: '46ac7f30ebf64c851a1b98991671a529d61b881c76e5d5321216a8ae77ac8ec7',
  },
  {
    filename: '007_pricing_sync_log.sql',
    sha256: '6d0c8ca7cf54c02d161921aa69529114c8f9282bf5e17b343788d2cccb419637',
  },
  {
    filename: '008_api_keys_pricing_admin_scope.sql',
    sha256: '6e5278eb721218366a8076c504b86630ede8203e9d1774765d2a5155e0ed87a4',
  },
  {
    filename: '010_users_and_memberships.sql',
    sha256: 'c8ddbb7838b6dfec3565cfc2293f59c4c3bf094a6a796512b1dc1664d2bc6466',
  },
  {
    filename: '011_builder_slug.sql',
    sha256: '6ded815966e73bb7aaf932413d0707bb93b436c5f3f7f2c3b7a893a1dcf12c37',
  },
  {
    filename: '012_auth_provider.sql',
    sha256: 'fa6349b725dc53f0b7b1285565a0b6395bf7e0de9a4b1b9a7b629a4ed164a105',
  },
  {
    filename: '013_webhook_secret_rotation.sql',
    sha256: '1a23ab86331a3e207045d4216810238fb35e6d0039e5a0909e4447661dfd8dd9',
  },
  {
    filename: '014_alert_history.sql',
    sha256: '9897901a07d8e2c41f0298694282da436a4dc69ec490e0f5c6c7006bd78015d0',
  },
  {
    filename: '015_builders_display.sql',
    sha256: 'e0070a8e6e3eaba298809cca744861939986ac3a450f0321ce41a9fcd6270d22',
  },
  {
    filename: '016_webhook_dlq_multichannel.sql',
    sha256: '50148ef96892d9e90e36cd130edb8cf4c7260eb783609fce0d6ad882031f73a1',
  },
  {
    filename: '017_rule_alert_channels.sql',
    sha256: '2d74f02ce1c524d6844cd1dc97fc066947e552185a569eea736f9a6fdece8a26',
  },
  {
    filename: '018_builder_feature_flags.sql',
    sha256: 'e677c2887cfa0974c903c35569ffac3af924f1c84bb74f1c6d48fcf0bed5fbeb',
  },
  {
    filename: '019_audit_log_actor.sql',
    sha256: 'cc7460bb5189c8b6887c37d1ba92475485695f9a451c9bdd5f5314204e4500e0',
  },
  {
    filename: '021_invoice_idempotency.sql',
    sha256: 'eb1539b1f6e6a02f841631838faeeabaffdd47b2fd1a1d5afb314206b6af7cf8',
  },
  {
    filename: '022_customer_pricing_versioned.sql',
    sha256: 'e747280faf1d8c78489eb77def996255e52d41720794c6672638a82c10186d62',
  },
  {
    filename: '023_invoices_cycle.sql',
    sha256: '6121b31c1e4b070ece760a2aef98f1081909aafdd53407683974e350c1842cec',
  },
  {
    filename: '024_builder_alert_config.sql',
    sha256: '2f97764686302d60c49398c9b7a2aadbefa82866329f04aceae72e112a44ea63',
  },
  {
    filename: '025_stripe_connect_capabilities.sql',
    sha256: 'b4d51b3a830869d2dc5699edce4c466748578d76dec4a91655069b020061e860',
  },
  {
    filename: '026_cost_sources_and_rule_status.sql',
    sha256: '1ffbc470baa80eeb9db66243c5f9dddc699c4fe1d2768cb74490ae1c8e3da882',
  },
  {
    filename: '027_api_keys_cost_sources_scope.sql',
    sha256: '5f846212dfaa4518aaa9db04a5b71f1ff3aa387fdc998a1cd6a9597ef2d23ea1',
  },
  {
    filename: '028_b4_rules.sql',
    sha256: 'd8c4e517a5ab780cc340103f603048143ac3df1a9f9d80985ba27026869d2c26',
  },
  {
    filename: '029_b4_portal.sql',
    sha256: 'a12f87abba5e16b94e1c777529522d63c6da20fa6ed921ed9e0d43066ece37d6',
  },
  {
    filename: '030_b4_anomaly_idempotency.sql',
    sha256: 'eba594fc0b4288c963472d0cf2248ca35eceef02fa3fa76dc4feaa152448d580',
  },
  {
    filename: '031_invoice_idempotency_composite_and_draft_key.sql',
    sha256: '647e10f7345bfa99ee86ebc656a2c3274eb682fb589b9e5f6d7d672317a7ff4f',
  },
  {
    filename: '032_track3_rules_portal_contracts.sql',
    sha256: 'c52ddbd29c803adb5835bb4fc34348fea6d3b7a2596057b73a84a27b0b2de711',
  },
  {
    filename: '033_portal_sessions.sql',
    sha256: 'd323eb66aaf7ba661257e2372f728ad74a11ef46a10ea061f6d9b1c2d2c01f2b',
  },
  {
    filename: '035_anomaly_status_expired.sql',
    sha256: '36d3d59f75b1552285d46c4024a088e585ff37f4de1d4646d3c5d1a153f908ce',
  },
  {
    filename: '036_portal_show_invoices_default_false.sql',
    sha256: 'b8e274d5e149fd2260f5c1101ece17ff6095414fdf8ae85413dd4e01310c7add',
  },
  {
    filename: '037_builders_tier_default_free.sql',
    sha256: 'c6b7bf4f488c744709489fa5ffe92509947d595d0f8859d3d23174d651dc8712',
  },
  {
    filename: '039_stripe_connect_event_log.sql',
    sha256: '4fb7a013749345d829fac3fccd357f5d8742135b37661efad10d8ee1cd277fc9',
  },
  {
    filename: '040_audit_log_partition_runway.sql',
    sha256: 'f02d00a1d45bfc92e9794c3655629108e242781d4143e0916ecea26eae116a95',
  },
  {
    filename: '041_rename_api_key_scopes.sql',
    sha256: 'e7323a19fe2db17c91d7a7c62f430c72d7a7187c54a8abba451f9df42f245af4',
  },
  {
    filename: '042_remove_customer_throttle_rule.sql',
    sha256: 'f3a0d72fe07b2b7f5ae3cc0a54f8ace3fe409dbf906a5c70fb0737bae421d652',
  },
  {
    filename: '043_custom_pricing_interval_invariants.sql',
    sha256: '797b7be550419aef33255989555bd67e4085006347afb167fc44eebd919fa9f0',
  },
  {
    filename: '044_custom_rule_requests.sql',
    sha256: 'efe959bff0c211613542afe2ed29c87b37f3d585e88b191b46592d73c8d63de9',
  },
  {
    filename: '045_flexible_provider_model_identifiers.sql',
    sha256: 'ba09a83dc374d0073c659879c5d34a169be88e30de1073e8a4ca1bc8266658f0',
  },
  {
    filename: '046_rls_hardening.sql',
    sha256: 'c827502a164ab77d1400fb5e3c28fd5a7d14ff34e0179ed5ca3b63143d734024',
  },
  {
    filename: '047_non_llm_policy.sql',
    sha256: 'f5a7e89d2dad29f4d58c2a0a1c269b0b719cd4dfa009f64afbf565de08ca044d',
  },
  {
    filename: '048_universal_api_key_scope.sql',
    sha256: '4c5f94c8c6e8b307399aa9783e93f7f5f48d938ad043205b0cfa527e4f2c87aa',
  },
  {
    filename: '049_backfill_builder_owner_memberships.sql',
    sha256: 'be2ab84f5df894efb2d911e1edf237eda09259ec7f46aca50508b85215f3bb91',
  },
] as const;

export const EXPECTED_SCHEMA_HEAD: string = '049_backfill_builder_owner_memberships.sql';
