import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isMainModule } from './db-migrate.js';
import {
  DEFAULT_MIGRATION_PHASE,
  listMigrationFiles,
  type MigrationPhase,
} from './db-migrate-core.js';

export interface MigrationManifestEntry {
  filename: string;
  sha256: string;
  phase: MigrationPhase;
}

export interface MigrationManifest {
  entries: MigrationManifestEntry[];
  head: string;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DEFAULT_ROOT_DIR = path.resolve(__dirname, '..');
const MANIFEST_RELATIVE_PATH = 'src/lib/db/migration-manifest.ts';

function tsStringLiteral(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

export async function buildMigrationManifest(rootDir: string): Promise<MigrationManifest> {
  const migrationsDir = path.resolve(rootDir, 'db/migrations');
  const files = await listMigrationFiles(migrationsDir);

  if (files.length === 0) {
    throw new Error(`No PostgreSQL migrations found in ${migrationsDir}`);
  }

  const entries = files.map((file) => ({
    filename: file.filename,
    sha256: file.checksum,
    phase: file.phase ?? DEFAULT_MIGRATION_PHASE,
  }));
  const head = entries.at(-1)?.filename;

  if (head === undefined) {
    throw new Error(`No PostgreSQL migrations found in ${migrationsDir}`);
  }

  return { entries, head };
}

export function renderMigrationManifestModule(manifest: MigrationManifest): string {
  const renderedEntries = manifest.entries
    .map(
      (entry) =>
        `  {
    filename: ${tsStringLiteral(entry.filename)},
    sha256: ${tsStringLiteral(entry.sha256)},
    phase: ${tsStringLiteral(entry.phase)},
  },`,
    )
    .join('\n');

  return `// GENERATED by scripts/generate-migration-manifest.ts — do not edit by hand.
// Regenerate after adding a migration: pnpm db:manifest
export type MigrationPhase = 'pre_roll' | 'post_roll';

export interface MigrationManifestEntry {
  filename: string;
  sha256: string;
  phase: MigrationPhase;
}

export const EXPECTED_MIGRATIONS: readonly MigrationManifestEntry[] = [
${renderedEntries}
] as const;

export const EXPECTED_SCHEMA_HEAD: string = ${tsStringLiteral(manifest.head)};
`;
}

async function main(): Promise<void> {
  const manifest = await buildMigrationManifest(DEFAULT_ROOT_DIR);
  const outputPath = path.resolve(DEFAULT_ROOT_DIR, MANIFEST_RELATIVE_PATH);

  await fs.writeFile(outputPath, renderMigrationManifestModule(manifest), 'utf8');
  console.log(
    `wrote ${MANIFEST_RELATIVE_PATH} (${manifest.entries.length} migrations, head ${manifest.head})`,
  );
}

if (isMainModule(import.meta.url, process.argv[1])) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
